"""Tests for the offline archive builder.

The script is not part of the package (it is maintainer tooling, run by hand),
so it is loaded from its path. The expensive parts — downloading wheels, zipping
— are not exercised here; what is covered is the logic that decides *before*
those minutes are spent, plus the interpreter probe that differs per machine.
"""

from __future__ import annotations

import argparse
import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_script() -> ModuleType:
    path = REPO_ROOT / "scripts" / "build_offline_archive.py"
    spec = importlib.util.spec_from_file_location("build_offline_archive", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


script = _load_script()


def test_out_must_be_a_zip_and_is_rejected_before_any_work() -> None:
    with pytest.raises(argparse.ArgumentTypeError):
        script.zip_destination("charles-mcp.tar")


def test_out_expands_a_quoted_home_shortcut() -> None:
    # Unquoted the shell expands ~; quoted it would otherwise become a literal
    # directory named "~" next to the repository.
    assert script.zip_destination("~/Downloads/charles-mcp.zip").is_absolute()


def test_pip_python_skips_an_interpreter_without_pip(monkeypatch: pytest.MonkeyPatch) -> None:
    """uv's venv has no pip, so the probe must fall through to the next candidate."""
    without_pip = sys.executable
    with_pip = "/usr/local/bin/python3"

    monkeypatch.setattr(script.shutil, "which", lambda _name: without_pip)
    monkeypatch.setattr(script.Path, "exists", lambda _self: True)

    def fake_probe(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        # Only one candidate answers, so the result also pins the search order.
        return subprocess.CompletedProcess(command, 0 if command[0] == with_pip else 1, "", "")

    monkeypatch.setattr(script.subprocess, "run", fake_probe)
    assert script.pip_python() == with_pip


def test_pip_python_reports_when_no_interpreter_has_pip(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(script.shutil, "which", lambda _name: None)
    monkeypatch.setattr(script.Path, "exists", lambda _self: True)
    monkeypatch.setattr(
        script.subprocess,
        "run",
        lambda command, **_kwargs: subprocess.CompletedProcess(command, 1, "", ""),
    )
    with pytest.raises(SystemExit, match="ensurepip"):
        script.pip_python()


def test_export_tree_unpacks_the_tracked_files_of_head(tmp_path: Path) -> None:
    tree = script.export_tree(tmp_path)

    assert tree == tmp_path / script.ARCHIVE_PREFIX
    assert (tree / "pyproject.toml").is_file()
    assert (tree / "charles_mcp" / "main.py").is_file()
    # The archive ships the tracked tree only: no history, no local junk.
    assert not (tree / ".git").exists()
    assert not (tree / ".venv").exists()
    assert not (tmp_path / "tree.tar").exists()


def test_export_requirements_counts_distributions_not_lines(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    exported = (
        "# generated by uv\n"
        "httpx==0.28.1 \\\n"
        "    --hash=sha256:aaa \\\n"
        "    --hash=sha256:bbb\n"
        "pydantic==2.12.0 \\\n"
        "    --hash=sha256:ccc\n"
    )
    monkeypatch.setattr(
        script,
        "run",
        lambda *_args, **_kwargs: subprocess.CompletedProcess([], 0, exported, ""),
    )

    target = tmp_path / "requirements-lock.txt"
    assert script.export_requirements(target) == 2
    assert target.read_text(encoding="utf-8") == exported


def test_build_litter_is_removed_from_the_tree_that_ships(tmp_path: Path) -> None:
    """setuptools writes build/ and *.egg-info into the staged copy the archive is made from."""
    (tmp_path / "build" / "lib").mkdir(parents=True)
    (tmp_path / "charles_mcp.egg-info").mkdir()
    (tmp_path / "charles_mcp").mkdir()
    (tmp_path / "pyproject.toml").write_text("[project]\n")

    removed = script.remove_build_litter(tmp_path)

    assert sorted(removed) == ["build", "charles_mcp.egg-info"]
    assert sorted(p.name for p in tmp_path.iterdir()) == ["charles_mcp", "pyproject.toml"]
